# -*- coding: utf-8 -*-
"""suz exercice_conditions.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jJzHI3eLRwENmQgB0F5S3E0edbyISsA-

# Exercices — Python : Structures Conditionnelles

Complète les exercices dans l'ordre. Le niveau augmente progressivement.

Dépose ce notebook dans le Drive partagé une fois terminé.

---
## Exercice 1 — Guidé

Les variables sont déclarées. Complète uniquement la structure conditionnelle.

ImmoPulse classe ses biens selon le prix au m² :

| Catégorie | Prix au m² |
|-----------|------------|
| Entrée de gamme | < 3 000 € |
| Marché courant | 3 000 € à 4 999 € |
| Premium | 5 000 € à 7 999 € |
| Luxe | ≥ 8 000 € |

Affiche la catégorie du bien. Teste ton code en changeant la valeur de `prix_m2`.
"""

prix_m2 = 4672.99

if prix_m2 >= 8000:
    print("Catégorie : Luxe")
elif prix_m2 >= 5000:
    print("Catégorie : Premium")
elif prix_m2 >= 3000:
    print("Catégorie : Marché courant")
else:
    print("Catégorie : Entrée de gamme")

prix_m2 = 7020

if prix_m2 >= 8000:
    print("Catégorie : Luxe")
elif prix_m2 >= 5000:
    print("Catégorie : Premium")
elif prix_m2 >= 3000:
    print("Catégorie : Marché courant")
else:
    print("Catégorie : Entrée de gamme")

prix_m2 = 9000

if prix_m2 >= 8000:
    print("Catégorie : Luxe")
elif prix_m2 >= 5000:
    print("Catégorie : Premium")
elif prix_m2 >= 3000:
    print("Catégorie : Marché courant")
else:
    print("Catégorie : Entrée de gamme")

"""---
## Exercice 2 — Semi-guidé

Les variables sont fournies. Écris toi-même toutes les conditions et tous les prints.

Une banque veut classer ses clients selon ces règles :

| Catégorie | Conditions |
|-----------|------------|
| **Premium** | Revenu > 4 000 € **ET** ancienneté > 5 ans **ET** aucun incident |
| **Standard+** | Revenu > 2 500 € **ET** ancienneté > 2 ans **ET** incidents ≤ 1 |
| **Standard** | Revenu > 1 500 € |
| **À risque** | Tout le reste |

Affiche la catégorie, puis affiche `"Éligible au crédit"` si Premium ou Standard+, sinon `"Dossier à étudier"`.
"""

revenu_mensuel = 2800
anciennete     = 3
incidents      = 0

if revenu_mensuel > 4000 and anciennete > 5 and incidents == 0:
    print("Catégorie : Premium")
    print("Éligible au crédit")
elif revenu_mensuel > 2500 and anciennete > 2 and incidents <= 1:
    print("Catégorie : Standard+")
    print("Éligible au crédit")
elif revenu_mensuel > 1500:
    print("Catégorie : Standard")
    print("Dossier à étudier")
else:
    print("Catégorie : À risque")
    print("Dossier à étudier")

revenu_mensuel = 5000
anciennete     = 1
incidents      = 0

if revenu_mensuel > 4000 and anciennete > 5 and incidents == 0:
    print("Catégorie : Premium")
    print("Éligible au crédit")
elif revenu_mensuel > 2500 and anciennete > 2 and incidents <= 1:
    print("Catégorie : Standard+")
    print("Éligible au crédit")
elif revenu_mensuel > 1500:
    print("Catégorie : Standard")
    print("Dossier à étudier")
else:
    print("Catégorie : À risque")
    print("Dossier à étudier")

"""---
## Exercice 3 — Autonome

Un cinéma applique la politique tarifaire suivante :

- Tarif normal : 12 €
- Moins de 12 ans : 7 €
- Étudiant (moins de 26 ans avec carte étudiante) : 8 €
- Senior (60 ans et plus) : 8 €
- Carte fidélité (peu importe l'âge) : −2 € sur le tarif applicable
- Séance du mercredi : −1 € supplémentaire pour tout le monde

Crée un script qui demande à l'utilisateur son âge, s'il est étudiant, s'il a une carte fidélité, et si c'est une séance du mercredi. Calcule et affiche le prix final de son billet.

Aucune variable, aucune condition n'est fournie. Pars de zéro.
"""

tarif_normal = 12
tarif_enfant = 7
tarif_etudiant = 8
tarif_senior = 8
reduction_fidelite = 2
reduction_mercredi = 1

age = int(input("Quel est votre âge ? "))
etudiant = input("Êtes-vous étudiant ? (oui/non) ") == "oui"
carte_fidelite = input("Avez-vous une carte fidélité ? (oui/non) ") == "oui"
mercredi = input("Est-ce une séance du mercredi ? (oui/non) ") == "oui"

if age < 12:
    prix = 7
elif etudiant and age < 26:
    prix = 8
elif age >= 60:
    prix = 8
else:
    prix = tarif_normal

if carte_fidelite:
    prix = prix - reduction_fidelite

if mercredi:
    prix = prix - reduction_mercredi

if prix < 0:
    prix = 0

print("Prix du billet :", prix, "€")

"""---
## Bonus

Ajoute une vérification : si le prix calculé est inférieur à 5 €, affiche un message d'erreur `"Tarif invalide — vérifier les conditions"`. Le prix ne peut pas descendre en dessous de 5 €.
"""

prix = 3
if prix < 5:
    print("Tarif invalide — vérifier les conditions")
    prix = 5

print("Prix du billet :", prix, "€")